import {
  BoldIcon,
  BrushIcon,
  CalendarIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsUpDownIcon,
  ChevronUpIcon,
  CircleIcon,
  GripHorizontalIcon,
  ItalicIcon,
  LassoSelectIcon,
  LoaderCircleIcon,
  MailOpenIcon,
  MinusIcon,
  MoonIcon,
  MoreHorizontalIcon,
  MousePointer2Icon,
  MoveIcon,
  MoveRightIcon,
  MoveUpIcon,
  PencilIcon,
  PipetteIcon,
  PlusIcon,
  SearchIcon,
  SlashIcon,
  SunIcon,
  UnderlineIcon,
  XIcon,
} from 'lucide-react';

/**
 * Represents a collection of icons.
 */
export const Icons = {
  Brush: BrushIcon,
  Calendar: CalendarIcon,
  Check: CheckIcon,
  ChevronDown: ChevronDownIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  ChevronsUpDown: ChevronsUpDownIcon,
  ChevronUp: ChevronUpIcon,
  Circle: CircleIcon,
  Close: XIcon,
  FontBold: BoldIcon,
  FontItalic: ItalicIcon,
  GripHorizontal: GripHorizontalIcon,
  LassoSelect: LassoSelectIcon,
  MailOpen: MailOpenIcon,
  Minus: MinusIcon,
  Moon: MoonIcon,
  MoreHorizontal: MoreHorizontalIcon,
  MousePointer2: MousePointer2Icon,
  Move: MoveIcon,
  MoveRight: MoveRightIcon,
  MoveUp: MoveUpIcon,
  Pencil: PencilIcon,
  Pipette: PipetteIcon,
  Plus: PlusIcon,
  Reload: LoaderCircleIcon,
  Search: SearchIcon,
  Slash: SlashIcon,
  Sun: SunIcon,
  Underline: UnderlineIcon,
};
