import {
  ArrowRightIcon,
  ArrowUpIcon,
  BellIcon,
  CalendarIcon,
  CaretDownIcon,
  CaretSortIcon,
  CaretUpIcon,
  CheckIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  Cross2Icon,
  CursorArrowIcon,
  DotFilledIcon,
  DotsHorizontalIcon,
  DragHandleHorizontalIcon,
  EnvelopeOpenIcon,
  FontBoldIcon,
  MagicWandIcon,
  MagnifyingGlassIcon,
  MinusIcon,
  MoonIcon,
  MoveIcon,
  Pencil1Icon,
  Pencil2Icon,
  PlusIcon,
  ReloadIcon,
  SlashIcon,
  SunIcon,
  UnderlineIcon,
} from '@radix-ui/react-icons';

/**
 * Represents a collection of icons.
 */
export const Icons = {
  ArrowRight: ArrowRightIcon,
  ArrowUp: ArrowUpIcon,
  Bell: BellIcon,
  Calendar: CalendarIcon,
  Check: CheckIcon,
  ChevronDown: CaretDownIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  ChevronsUpDown: CaretSortIcon,
  ChevronUp: CaretUpIcon,
  Close: Cross2Icon,
  CursorArrow: CursorArrowIcon,
  DotFilled: DotFilledIcon,
  EnvelopeOpen: EnvelopeOpenIcon,
  FontBold: FontBoldIcon,
  FontItalic: FontBoldIcon,
  GripHorizontal: DotsHorizontalIcon,
  MagicWand: MagicWandIcon,
  Minus: MinusIcon,
  Moon: MoonIcon,
  MoreHorizontal: DragHandleHorizontalIcon,
  Move: MoveIcon,
  Pencil1: Pencil1Icon,
  Pencil2: Pencil2Icon,
  Plus: PlusIcon,
  Reload: ReloadIcon,
  Search: MagnifyingGlassIcon,
  Slash: SlashIcon,
  Sun: SunIcon,
  Underline: UnderlineIcon,
};
