name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      NEXT_PUBLIC_DOCSEARCH_API_KEY: ${{ secrets.NEXT_PUBLIC_DOCSEARCH_API_KEY }}
      NEXT_PUBLIC_DOCSEARCH_APP_ID: ${{ secrets.NEXT_PUBLIC_DOCSEARCH_APP_ID }}
      NEXT_PUBLIC_DOCSEARCH_INDEX_NAME: ${{ vars.NEXT_PUBLIC_DOCSEARCH_INDEX_NAME }}
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/setup

      - name: Branch Checks
        uses: ./.github/actions/checks

      - name: Build All
        uses: ./.github/actions/build-all
